import Link from "next/link";
import { PageHero, PageShell } from "@/components/PageShell";

export const metadata = {
  title: "Privacy policy",
  description:
    "YTMP privacy policy: what data we collect for licenses, orders, and support — and what stays on your PC.",
};

const lastUpdated = "August 4, 2026";

export default function PrivacyPage() {
  return (
    <PageShell narrow>
      <PageHero
        kicker="Legal"
        title="Privacy policy"
        lead="This policy explains what personal data YTMP collects, why we process it, how long we keep it, and your choices. Media downloads and local conversions stay on your computer — we do not receive your media libraries."
      />
      <p className="legal-meta">Last updated: {lastUpdated}</p>

      <div className="prose-panel">
        <h2>1. Scope</h2>
        <p>
          This policy covers the YTMP website, license and order APIs, admin systems used to fulfill
          subscriptions, transactional email, and interactions between the Windows application and
          our license servers. It does not govern third-party platforms (YouTube, Spotify,
          SoundCloud, payment processors, hosting providers) that have their own policies.
        </p>

        <h2>2. Data controller</h2>
        <p>
          The operator of YTMP is the controller of personal data described here. For privacy
          requests, contact us via the{" "}
          <Link href="/support">Support</Link> page and use the subject “Privacy request”.
        </p>

        <h2>3. What we collect</h2>
        <h3>3.1 Information you provide</h3>
        <ul>
          <li>
            <strong>Order details</strong> — name (if provided), email address, selected plan,
            notes, coupon codes
          </li>
          <li>
            <strong>Payment references</strong> — transfer IDs, proof notes, or confirmation
            details you send so we can mark an order paid (we are not a bank; card data should not
            be emailed to us)
          </li>
          <li>
            <strong>Support messages</strong> — content of emails and attachments you send
            (including logs)
          </li>
        </ul>
        <h3>3.2 License and device data</h3>
        <ul>
          <li>
            <strong>License keys</strong> and subscription state (active, expired, revoked, free-day
            extensions)
          </li>
          <li>
            <strong>Device fingerprint / hardware identifiers</strong> generated by the app for
            seat enforcement and fraud prevention
          </li>
          <li>
            <strong>License check metadata</strong> — timestamps of activations and validation
            requests, approximate result (success / failure reason), and technical context required
            to operate the check securely
          </li>
        </ul>
        <h3>3.3 Technical and website data</h3>
        <ul>
          <li>
            Server logs from our API and hosting platforms (IP address, user agent, request path,
            time, error codes)
          </li>
          <li>
            Operational metrics on our hosting provider (e.g. Vercel / database host) under their
            processing terms
          </li>
          <li>
            Cookies or local storage only if the website needs them for session-like features (most
            marketing pages work without account cookies)
          </li>
        </ul>
        <h3>3.4 What we do not collect as a rule</h3>
        <ul>
          <li>
            The contents of media files you download or convert — processing happens on your PC
          </li>
          <li>Your full local disk listings or browser history</li>
          <li>Passwords to YouTube, Spotify, SoundCloud, or other media accounts for normal use</li>
        </ul>
        <p>
          Application logs such as <code>launcher.log</code> remain under{" "}
          <code>%LOCALAPPDATA%\YTMP</code> until you choose to send them to support.
        </p>

        <h2>4. Why we process data (purposes)</h2>
        <ul>
          <li>
            <strong>Provide the service</strong> — create orders, issue and validate licenses,
            email keys and fulfillment notices
          </li>
          <li>
            <strong>Payments and accounting</strong> — match transfers to orders, prevent double
            fulfillment, handle refunds where applicable
          </li>
          <li>
            <strong>Security and abuse prevention</strong> — detect shared keys, automated attacks,
            and fraudulent trial abuse
          </li>
          <li>
            <strong>Customer support</strong> — diagnose activation and software issues
          </li>
          <li>
            <strong>Legal compliance</strong> — retain records when required by tax, accounting, or
            dispute rules
          </li>
          <li>
            <strong>Product improvement</strong> — aggregate, non-identifying usage of license check
            success/failure rates (not your media)
          </li>
        </ul>

        <h2>5. Legal bases (where applicable)</h2>
        <p>
          If you are in a region that requires a legal basis under laws such as the GDPR, we
          typically rely on: (a) performance of a contract (providing a paid or trial license);
          (b) legitimate interests (securing the service, preventing fraud, improving reliability);
          and (c) legal obligation when retaining certain transaction records. Where consent is
          required for a specific optional processing, we will request it separately.
        </p>

        <h2>6. Retention</h2>
        <ul>
          <li>
            <strong>Orders and licenses</strong> — retained while the relationship is active and for
            a reasonable period afterward for disputes, renewals, and fraud prevention (often up to
            several years for commercial records)
          </li>
          <li>
            <strong>Support emails</strong> — kept as long as needed to resolve the issue and for
            follow-up quality, then deleted or archived under routine inbox policies
          </li>
          <li>
            <strong>Server logs</strong> — short to medium term depending on host defaults and
            security needs
          </li>
          <li>
            <strong>Local app data</strong> — under your control on the Windows machine; uninstall
            or deleting <code>%LOCALAPPDATA%\YTMP</code> removes local records without deleting
            server-side licenses
          </li>
        </ul>

        <h2>7. Sharing and processors</h2>
        <p>We do not sell personal data. We share data only with:</p>
        <ul>
          <li>
            <strong>Infrastructure providers</strong> — hosting, database, and email delivery
            services that process data on our instructions
          </li>
          <li>
            <strong>Operators / admins</strong> — people who mark orders paid and manage licenses
          </li>
          <li>
            <strong>Professional advisors or authorities</strong> — when required by law or to
            defend legal claims
          </li>
        </ul>
        <p>
          Payment instructions may point you to third-party rails (bank transfer, payment apps,
          etc.). Those services process payment data under their own privacy policies.
        </p>

        <h2>8. International transfers</h2>
        <p>
          Servers and processors may be located in countries other than yours (for example if we
          host on US or EU cloud regions). Where required, we rely on appropriate safeguards offered
          by those providers (such as standard contractual clauses) or other lawful transfer
          mechanisms.
        </p>

        <h2>9. Security</h2>
        <p>
          We use industry-typical measures for a SaaS license stack: HTTPS in transit, access
          controls for admin tools, and least-privilege practices for production databases. No
          method of transmission or storage is perfectly secure; protect your license email and do
          not publish keys.
        </p>

        <h2>10. Your rights</h2>
        <p>
          Depending on your location, you may have rights to access, correct, delete, or export
          certain personal data, object to or restrict processing, and lodge a complaint with a
          supervisory authority. To exercise rights, contact support with enough detail to verify
          you own the order email. We may retain data when we have a lawful reason (for example
          completed invoices or fraud records).
        </p>
        <p>
          You can uninstall YTMP and delete local folders at any time. Deleting local data does not
          automatically cancel a paid subscription — contact support if you need key revocation
          after a refund or dispute.
        </p>

        <h2>11. Children</h2>
        <p>
          YTMP is not directed at children under 16 (or the minimum age in your region). We do not
          knowingly collect personal data from children. If you believe a child provided data,
          contact us to delete it.
        </p>

        <h2>12. Automated decisions</h2>
        <p>
          License validation may automatically allow or deny app features based on subscription
          status and device checks. That is necessary to provide the product, not to profile you
          for marketing.
        </p>

        <h2>13. Changes to this policy</h2>
        <p>
          We may update this page and change the “Last updated” date. Material changes that
          affect how we use personal data will be posted on the website; where appropriate we may
          also notify active license emails.
        </p>

        <h2>14. Related documents</h2>
        <ul>
          <li>
            <Link href="/legal/terms">Terms of use</Link> — license and acceptable use
          </li>
          <li>
            <Link href="/docs">Docs</Link> — local paths and how the app works
          </li>
          <li>
            <Link href="/support">Support</Link> — contact channel for privacy requests
          </li>
        </ul>
      </div>
    </PageShell>
  );
}
